apiVersion: v1
kind: Service
metadata:
  name: password-app-svc
  namespace: lab-server
spec:
  selector:
    app: password-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32405
  type: NodePort
